# Generated by Django 4.0.6 on 2022-07-17 14:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kateqoriyanın adı')),
                ('slag', models.SlugField(max_length=250, unique=True, verbose_name='Kateqoriyanın slaqı')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='post.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Teq adı')),
                ('slag', models.SlugField(max_length=250, unique=True, verbose_name='Teqin slaqı')),
            ],
            options={
                'verbose_name': 'Teq',
                'verbose_name_plural': 'Teq',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Şəkil')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Baxış sayı')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayım tarixi')),
                ('published', models.BooleanField(default=False, verbose_name='Aktivlik')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='post.category', verbose_name='Kateqoriya')),
                ('tag', models.ManyToManyField(related_name='post_tags', to='post.tag', verbose_name='Teq')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbər',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('text', models.TextField(verbose_name='Mətn')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma tarixi')),
                ('published', models.BooleanField(default=True, verbose_name='Aktivlik')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='post.post', verbose_name='Xəbər')),
            ],
            options={
                'verbose_name': 'Şərh',
                'verbose_name_plural': 'Şərh',
                'ordering': ['-create_at'],
            },
        ),
    ]
