# Generated by Django 4.0.6 on 2022-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/post/%Y/%m/%d/', verbose_name='Şəkil'),
        ),
    ]
