# Generated by Django 4.0.6 on 2022-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=250, verbose_name='Sifarişçi')),
                ('customer_url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('image', models.ImageField(upload_to='image/advertising/%Y/%m/%d/', verbose_name='Şəkil')),
                ('published', models.BooleanField(default=False, verbose_name='Aktivlik')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yayım tarixi')),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklam',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefon')),
                ('mob', models.CharField(blank=True, max_length=60, null=True, verbose_name='Mobil')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ünvan')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('soc_link_1', models.URLField(blank=True, null=True, verbose_name='Sosial link 1')),
                ('soc_icon_1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sosial ikon 1')),
                ('soc_link_2', models.URLField(blank=True, null=True, verbose_name='Sosial link 2')),
                ('soc_icon_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sosial ikon 2')),
                ('soc_link_3', models.URLField(blank=True, null=True, verbose_name='Sosial link 3')),
                ('soc_icon_3', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sosial ikon 3')),
                ('soc_link_4', models.URLField(blank=True, null=True, verbose_name='Sosial link 4')),
                ('soc_icon_4', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sosial ikon 4')),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqə',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/logo/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Loqotip',
                'verbose_name_plural': 'Loqotip',
            },
        ),
    ]
