# Generated by Django 4.0.6 on 2022-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='mob',
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(help_text='Şəkil ölçüsü 400X500', upload_to='image/advertising/%Y/%m/%d/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='soc_icon_1',
            field=models.CharField(blank=True, help_text=('fa-facebook', 'fa-instagram', 'fa-linkedin', 'fa-twitter', 'fa-vk'), max_length=60, null=True, verbose_name='Sosial ikon 1'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='soc_icon_2',
            field=models.CharField(blank=True, help_text=('fa-facebook', 'fa-instagram', 'fa-linkedin', 'fa-twitter', 'fa-vk'), max_length=60, null=True, verbose_name='Sosial ikon 2'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='soc_icon_3',
            field=models.CharField(blank=True, help_text=('fa-facebook', 'fa-instagram', 'fa-linkedin', 'fa-twitter', 'fa-vk'), max_length=60, null=True, verbose_name='Sosial ikon 3'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='soc_icon_4',
            field=models.CharField(blank=True, help_text=('fa-facebook', 'fa-instagram', 'fa-linkedin', 'fa-twitter', 'fa-vk'), max_length=60, null=True, verbose_name='Sosial ikon 4'),
        ),
    ]
