# Generated by Django 4.0.6 on 2022-07-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Şəkil')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Baxış sayı')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayım tarixi')),
                ('published', models.BooleanField(default=False, verbose_name='Aktivlik')),
                ('author', models.ForeignKey(default='account.MyUser', on_delete=django.db.models.deletion.CASCADE, related_name='slider_author', to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_category', to='post.category', verbose_name='Kateqoriya')),
                ('tag', models.ManyToManyField(related_name='slider_tags', to='post.tag', verbose_name='Teq')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slayder',
                'ordering': ['-create_at'],
            },
        ),
    ]
