# Generated by Django 4.0.6 on 2022-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/slider/%Y/%m/%d/', verbose_name='Şəkil'),
        ),
    ]
